local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "poems"
    label: "شعرها"
    folder: "src/content/poems"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ", name: "date", widget: "datetime" }
      - { label: "نام شاعر", name: "author", widget: "string", required: false }
      - { label: "تصویر", name: "image", widget: "image", required: false }
      - { label: "متن شعر", name: "body", widget: "text" }

  - name: "stories"
    label: "داستان‌ها"
    folder: "src/content/stories"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "خلاصه", name: "desc", widget: "string" }
      - { label: "تاریخ", name: "date", widget: "datetime" }
      - { label: "تصویر", name: "img", widget: "image", required: false }
      - { label: "متن داستان", name: "body", widget: "markdown" }

  - name: "notes"
    label: "یادداشت‌ها"
    folder: "src/content/notes"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ", name: "date", widget: "datetime" }
      - { label: "تصویر", name: "img", widget: "image", required: false }
      - { label: "متن یادداشت", name: "body", widget: "markdown" }